# EXCLUDED DIRECTORIES
excluded:
- tl-ios-demo/Resources/*
- Derived/Sources/**
- Frameworks
- Pods
- Products
- Tuist

# GLOBAL SETTINGS
identifier_name: # https://realm.github.io/SwiftLint/identifier_name.html
  min_lenght: 3
  max_lenght: 50
  excluded: # excluded via string array
    - id

nesting: # https://realm.github.io/SwiftLint/nesting.html
  type_level: 2

function_body_length: 100 # https://realm.github.io/SwiftLint/function_body_length.html
function_parameter_count: 5 # https://realm.github.io/SwiftLint/function_parameter_count.html

line_length: 500 # https://realm.github.io/SwiftLint/line_length.html
file_length: 1100 # https://realm.github.io/SwiftLint/file_length.html

cyclomatic_complexity: # https://realm.github.io/SwiftLint/cyclomatic_complexity.html
  warning: 10
  ignores_case_statements: true

closure_body_length:
  warning: 100
  error: 100

disabled_rules:
- opening_brace # https://realm.github.io/SwiftLint/opening_brace.html
- todo # https://realm.github.io/SwiftLint/todo.html
- trailing_comma # https://realm.github.io/SwiftLint/trailing_comma.html
- type_name # https://realm.github.io/SwiftLint/type_name.html
- redundant_string_enum_value # https://realm.github.io/SwiftLint/redundant_string_enum_value.html
- multiple_closures_with_trailing_closure # https://realm.github.io/SwiftLint/multiple_closures_with_trailing_closure.html

opt_in_rules:
- anyobject_protocol # https://realm.github.io/SwiftLint/anyobject_protocol.html
- array_init # https://realm.github.io/SwiftLint/array_init.html
- closure_body_length # https://realm.github.io/SwiftLint/closure_body_length.html
- closure_end_indentation # https://realm.github.io/SwiftLint/closure_end_indentation.html
- closure_spacing # https://realm.github.io/SwiftLint/closure_spacing.html
- collection_alignment # https://realm.github.io/SwiftLint/collection_alignment.html
- contains_over_filter_count # https://realm.github.io/SwiftLint/contains_over_filter_count.html
- contains_over_filter_is_empty # https://realm.github.io/SwiftLint/contains_over_filter_is_empty.html
- contains_over_first_not_nil # https://realm.github.io/SwiftLint/contains_over_first_not_nil.html
- contains_over_range_nil_comparison # https://realm.github.io/SwiftLint/contains_over_range_nil_comparison.html
- discouraged_object_literal # https://realm.github.io/SwiftLint/discouraged_object_literal.html
- empty_collection_literal # https://realm.github.io/SwiftLint/empty_collection_literal.html
- empty_string # https://realm.github.io/SwiftLint/empty_string.html
- empty_xctest_method # https://realm.github.io/SwiftLint/empty_xctest_method.html
- explicit_init # https://realm.github.io/SwiftLint/explicit_init.html
- fatal_error_message # https://realm.github.io/SwiftLint/fatal_error_message.html
- first_where # https://realm.github.io/SwiftLint/first_where.html
- flatmap_over_map_reduce # https://realm.github.io/SwiftLint/flatmap_over_map_reduce.html
- force_unwrapping # https://realm.github.io/SwiftLint/force_unwrapping.html
- identical_operands # https://realm.github.io/SwiftLint/identical_operands.html
- joined_default_parameter # https://realm.github.io/SwiftLint/joined_default_parameter.html
- last_where # https://realm.github.io/SwiftLint/last_where.html
- legacy_multiple # https://realm.github.io/SwiftLint/legacy_multiple.html
- legacy_random # https://realm.github.io/SwiftLint/legacy_random.html
- literal_expression_end_indentation # https://realm.github.io/SwiftLint/literal_expression_end_indentation.html
- lower_acl_than_parent # https://realm.github.io/SwiftLint/lower_acl_than_parent.html
- modifier_order # https://realm.github.io/SwiftLint/modifier_order.html
- multiline_parameters # https://realm.github.io/SwiftLint/multiline_parameters.html
- no_extension_access_modifier # https://realm.github.io/SwiftLint/no_extension_access_modifier.html
- no_space_in_method_call # https://realm.github.io/SwiftLint/no_space_in_method_call.html
- object_literal # https://realm.github.io/SwiftLint/object_literal.html
- operator_usage_whitespace # https://realm.github.io/SwiftLint/operator_usage_whitespace.html
- optional_enum_case_matching # https://realm.github.io/SwiftLint/optional_enum_case_matching.html
- orphaned_doc_comment # https://realm.github.io/SwiftLint/orphaned_doc_comment.html
- overridden_super_call # https://realm.github.io/SwiftLint/overridden_super_call.html
- prefer_self_type_over_type_of_self # https://realm.github.io/SwiftLint/prefer_self_type_over_type_of_self.html
- prohibited_super_call # https://realm.github.io/SwiftLint/prohibited_super_call.html
- quick_discouraged_focused_test # https://realm.github.io/SwiftLint/quick_discouraged_focused_test.html
- quick_discouraged_pending_test # https://realm.github.io/SwiftLint/quick_discouraged_pending_test.html
- raw_value_for_camel_cased_codable_enum # https://realm.github.io/SwiftLint/raw_value_for_camel_cased_codable_enum.html
- redundant_nil_coalescing # https://realm.github.io/SwiftLint/redundant_nil_coalescing.html
- redundant_type_annotation # https://realm.github.io/SwiftLint/redundant_type_annotation.html
- required_enum_case # https://realm.github.io/SwiftLint/required_enum_case.html
- sorted_first_last # https://realm.github.io/SwiftLint/sorted_first_last.html
- sorted_imports # https://realm.github.io/SwiftLint/sorted_imports.html
- static_operator # https://realm.github.io/SwiftLint/static_operator.html
- strong_iboutlet # https://realm.github.io/SwiftLint/strong_iboutlet.html
- toggle_bool # https://realm.github.io/SwiftLint/toggle_bool.html
- unneeded_parentheses_in_closure_argument # https://realm.github.io/SwiftLint/unneeded_parentheses_in_closure_argument.html
- unowned_variable_capture # https://realm.github.io/SwiftLint/unowned_variable_capture.html
- unused_import # https://realm.github.io/SwiftLint/unused_import.html
- unused_declaration # https://realm.github.io/SwiftLint/unused_declaration.html
- xct_specific_matcher # https://realm.github.io/SwiftLint/xct_specific_matcher.html
- xctfail_message # https://realm.github.io/SwiftLint/xctfail_message.html
- yoda_condition # https://realm.github.io/SwiftLint/yoda_condition.html

